// ------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated.
//
//     - To turn off auto-generation set:
//
//         [Jenkins (AutoGenerate = false)]
//
//     - To trigger manual generation invoke:
//
//         nuke --generate-configuration Jenkins --host Jenkins
//
// </auto-generated>
// ------------------------------------------------------------------------------

pipeline {
  agent { label 'sad' }
  environment {
    IS_UNIX = isUnix()
  } // environment
  stages {
    stage('Compile') {
      steps {
        nuke 'Restore Compile --skip'
      } // steps
    } // stage('Compile')
    stage('Pack') {
      steps {
        nuke 'Pack --skip'
      } // steps
    } // stage('Pack')
    stage('Test') {
      steps {
        nuke 'Test --skip'
      } // steps
    } // stage('Test')
    stage('Coverage') {
      steps {
        nuke 'Coverage --skip'
      } // steps
    } // stage('Coverage')
  } // stages
} // pipeline

void nuke(String args) {
  if (Boolean.valueOf(env.IS_UNIX)) {
    sh "build.sh $args"
  }
  else {
    powershell "build.ps1 $args"
  }
}
